/*
    THIS FILE IS AUTO-GENERATED.
    DO NOT MAKE ANY CHANGES HERE!
*/
/*
    THIS FILE IS *NOT* AUTO-GENERATED.
    
    IT'S JUST A WORKAROUND FOR MISSING CONFIGURATION SCRIPTS
    AT THE MOMENT.
    
    **TESTING**
*/

#if !TESTARCH

#define SYSTEM_BYTEORDER "01234567"

#else

#define SYSTEM_BYTEORDER "32107654"

#endif

#define TARGET_BYTEORDER "23016745"

#include <inttypes.h>
