/*
    THIS FILE IS AUTO-GENERATED.
    DO NOT MAKE ANY CHANGES HERE!
*/
/*
    THIS FILE IS *NOT* AUTO-GENERATED.
    
    IT'S JUST A WORKAROUND FOR MISSING CONFIGURATION SCRIPTS
    AT THE MOMENT.
    
    **TESTING**
*/

#include <inttypes.h>

#define SYSTEM_BYTEORDER "01234567"
#define TARGET_BYTEORDER "01234567"
