/*
    THIS FILE IS AUTO-GENERATED.
    DO NOT MAKE ANY CHANGES HERE!
*/
/*
    THIS FILE IS *NOT* AUTO-GENERATED.
    
    IT'S JUST A WORKAROUND FOR MISSING CONFIGURATION SCRIPTS
    AT THE MOMENT.
    
    **TESTING**
*/

#include <inttypes.h>

#define SYSTEM_BYTEORDER16 "01"
#define TARGET_BYTEORDER16 "01"
#define SYSTEM_BYTEORDER32 "0123"
#define TARGET_BYTEORDER32 "0123"
#define SYSTEM_BYTEORDER64 "01234567"
#define TARGET_BYTEORDER64 "01234567"
